# Index lookup for bands with multiple Metallum results
# 'None' indicates band is not in Metallum archives
metallum_index_lookup = {
    'Angel': None,
    'Autopsy': 1,
    'Black Death': 6,
    'Blasphemy': 0,
    'Cacophony': 1,
    'DEMON': 4,
    'Dark Angel': 1,
    'Dismember': 1,
    'Exciter': 0,
    'Gothic': None,
    'Holocaust': 9,
    'Holy Terror': 1,
    'Necrophagia': 1,
    'Overkill': 3,
    'Pentagram': 3,
    'Pestilence': 2,
    'Poison': 3,
    'Raven': 3,
    'Razor': 0,
    'Repulsion': 0,
    'Sabbat': 1,
    'Sanctuary': 5,
    'Satan': 6,
    'Savage': 6,
    'Slaughter': None,
    'Slayer': 1,
    'Sodom': 0,
    'Suffocation': 5,
    'Triumph': None,
    'Trouble': 1,
    'Warlock': 1,
    'Winter': 2,
}
